project:
  type: website

website:
  title: IMPACT OF MACROECONOMIC FACTORS ON EMPLOYMENT MARKET
  page-footer: 
    left: "Copyright 2023, Yujie Chen" 
    right: 
      - icon: github
        href: https://github.com/YujieChen20/Time-Series
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - about.qmd
      - introduction.qmd
      - sources.qmd
      - viz.qmd
      - eda.qmd
      - models.qmd
      - arimax.qmd
      - financial.qmd
      - deepLearning.ipynb
      - conclusions.qmd
  navbar:
    title: IMPACT OF MACROECONOMIC FACTORS ON EMPLOYMENT MARKET
   

format:
  html:
    theme: sketchy
    code-fold: true
    code-summary: "Show the code"
    css: styles.css
    toc: true

editor: visual

